### ISSUE TITLE
Requirements Gathering

### ISSUE THREAD

**Issue by aquaaerobicsystem** [aquaaerobicsystem/aerationandmixing#1]
See attached 5 spreadhseets, Still waiting on 9 spreadsheets as of 1/26/2021 - Chuck
 
[Spreadsheets.zip](https://github.com/aquaaerobicsystem/aerationandmixing/files/5874375/Spreadsheets.zip)

**Comment by chukon** [comment]
Waiting on one more spreadsheet from Alan

**Comment by chukon** [comment]
Waiting on sizes for basins for drag and drop environment

**Comment by aquaaerobicsystem** [comment]
Alan,

I need the most recent spreadsheet examples for completed projects with below basin types?

Activated Sludge/Anoxic Basins/Aqua MB/Aqua SBR/Aqua MSBR (See #11 )
Aerobic Digester/Sludge Holding/MBR 1-2% Solids Volume (See #12 )
Aerobic Digester/Sludge Holding 3% Solids Volume (See #13 )
Aerobic Digester/Sludge Holding 4% Solids Volume (See #14 )
Complete Mix Lagoon (See #15 )
Equalization Basin (See #16 )
Partial Mix Lagoon (See #17 )
Algae Control (See #18 )
Irregular Mixing Regime (See #19 )

Thanks, 
Chuck
