### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by aquaaerobicsystem** [aquaaerobicsystem/aerationandmixing#2]
Pending requirements completed #1 

[App Layout Screens

[Click here to view slides](https://docs.google.com/presentation/d/1ZGQoKW3pFW_JcFAMZJgao3nT5WuFf-UMFtlTPxCCZc0/edit?usp=sharing)

**Comment by chukon** [comment]
[App Layout Screens

[Click here to view slides](https://docs.google.com/presentation/d/1ZGQoKW3pFW_JcFAMZJgao3nT5WuFf-UMFtlTPxCCZc0/edit?usp=sharing)
