### ISSUE TITLE
Drag and Drop Basin

### ISSUE THREAD

**Issue by aquaaerobicsystem** [aquaaerobicsystem/aerationandmixing#5]
Web based drag and drop basin creation tool

**Comment by aquaaerobicsystem** [comment]
R&D layout. Modified exanoke from rectangles to circles layout

https://aquaaerobicsystemsinc.github.io/draganddropbasin/

**Comment by aquaaerobicsystem** [comment]
waiting on sizes of circular basins from Alan

**Comment by aquaaerobicsystem** [comment]
@Alan-Rice Reminder for different basin circular sizes for drag and drop component.

**Comment by Alan-Rice** [comment]
Chuck,

Please drop Alan from this list.

Thanks,

Bill Decker
Vice President & General Manager
Equipment and Services Group

AQUA-AEROBIC SYSTEMS, INC.
6306 N. Alpine Road
Loves Park, IL  61111-7655
Ph: 815-639-4423
Cell: 815-262-7188
E-Mail: ***@***.******@***.***>
www.aqua-aerobic.com<http://www.aqua-aerobic.com/>
Follow Us:LinkedIn<https://www.linkedin.com/company/aqua-aerobic-systems-inc-> and Twitter<https://twitter.com/AquaAerobic>

 [Aqua_Logo_EMAIL_Signature]

**Comment by ckonkolaqua** [comment]
Will do
